### ISSUE TITLE
After auth get "get containers error"

### ISSUE THREAD

**Issue by seliverstov-maxim** [nightlord189/docklogkeeper#10]
docker-compose.yml
```
version: "3"
services:
  docklogkeeper:
    container_name: docklogkeeper
    image: nightlord189/docklogkeeper:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docklogkeeper:/logs
    ports:
      - 3010:3010
    environment:
      - PASSWORD=admin

volumes:
  docklogkeeper:
```

log
```
{"log_level":"debug","component":"docklogkeeper","time":"2024-01-17T06:18:24Z","message":"triggers cache reloaded"}
{"log_level":"info","component":"docklogkeeper","containers":[{"ID":"aa93534c58666e7b3d23c15cfde11e634825cea9eec12b1ef360a414e0c129c3","Name":"doclogkeeper-docklogkeeper-run-5da1cb8a34e6"},{"ID":"d20dbc8f64276db8a3845fd86dc9af0c93d097abb922689ca2e43187600bf487","Name":"my-project-web-1"},{"ID":"1bd686ff33b55ef3f83902e2961486c08a5062a58abf1acf3fd39e0eab471a7e","Name":"my-project-redis-1"},{"ID":"ff650d2a79607969cccd0135e81ddd03358915bd72017180dfe837b5598a9e02","Name":"my-project-db-1"}],"time":"2024-01-17T06:18:24Z","message":"start reading 4 already existing containers"}
{"log_level":"info","component":"docklogkeeper","time":"2024-01-17T06:18:24Z","message":"start reading logs of container [d20dbc8f64276db8a3845fd86dc9af0c93d097abb922689ca2e43187600bf487, my-project-web-1]"}
{"log_level":"info","component":"docklogkeeper","time":"2024-01-17T06:18:24Z","message":"start reading logs of container [ff650d2a79607969cccd0135e81ddd03358915bd72017180dfe837b5598a9e02, my-project-db-1]"}
{"log_level":"info","component":"docklogkeeper","time":"2024-01-17T06:18:24Z","message":"start reading logs of container [1bd686ff33b55ef3f83902e2961486c08a5062a58abf1acf3fd39e0eab471a7e, my-project-redis-1]"}
{"log_level":"info","component":"docklogkeeper","time":"2024-01-17T06:18:24Z","message":"start reading logs of container [aa93534c58666e7b3d23c15cfde11e634825cea9eec12b1ef360a414e0c129c3, doclogkeeper-docklogkeeper-run-5da1cb8a34e6]"}
```
OS: Apple M1 - Sonoma 14.2.1
