### ISSUE TITLE
Problem with image architecture and docker socket proxy

### ISSUE THREAD

**Issue by shyonae** [nightlord189/docklogkeeper#5]
Hi!

I'm having two issues here. The first one is that, when I try to spin up the container from my Ubuntu machine, I get a warning: `The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested.`

EDIT: I'm using Ubuntu 22.04LTS to spin this container up,

The second issue is when the container runs, these are the logs:
```
start #1
2023-09-03T11:34:46+02:00 start #2 | log_level=debug component=docklogkeeper
current directory /
current executable /main
2023/09/03 11:34:46 goose: no migrations to run. current version: 1
2023/09/03 11:34:46 error on init docker: unable to parse docker host `dockerproxy`
2023-09-03T11:34:46+02:00 create docker client error | log_level=error component=docklogkeeper error=unable to parse docker host `dockerproxy`
```

For clarity, here's my docker compose, with other services that are up and running currently:
```
version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - managementStackNetwork
    - socketProxyNetwork

x-authelia-conf: &authelia
  labels:
    - swag=enable
    - swag_auth=authelia

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}
  DOCKER_HOST: dockerproxy

services:
  portainer:
    command: -H tcp://dockerproxy:2375
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      <<: *environment
    <<: [ *default_conf, *authelia ]
    ports:
      - 9000:9000
    volumes:
      - ${DOCKERCONFDIR}/portainer:/data
      - ${DOCKERSTORAGEDIR}:/storage

  watchtower:
    image: containrrr/watchtower
    command: -H tcp://dockerproxy:2375
    container_name: watchtower
    environment:
      <<: *environment
      WATCHTOWER_SCHEDULE: "0 0 03 * * *"
      WATCHTOWER_CLEANUP: "true"
    <<: *default_conf

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      <<: *environment
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/homarr/configs:/app/data/configs
      - ${DOCKERCONFDIR}/homarr/icons:/app/public/icons
    ports:
      - 7575:7575

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      <<: *environment
    <<: [ *default_conf, *authelia ]
    volumes:
      - ${DOCKERCONFDIR}/uptime-kuma:/app/data
    ports:
      - 3001:3001

  docklogkeeper:
    container_name: docklogkeeper
    image: nightlord189/docklogkeeper:latest
    command: -H tcp://dockerproxy:2375
    volumes:
      - ${DOCKERCONFDIR}/docklogkeeper:/logs
    environment:
      <<: *environment
      PASSWORD: ${DOCKLOGKEEPER_PWD}
    <<: *default_conf
    ports:
      - 3010:3010

networks:
  managementStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
```

I already tried without the `command: -H tcp://dockerproxy:2375` line, but it wouldn't work.
